### ISSUE TITLE
Map locks to center and cannot be scrolled

### ISSUE THREAD

**Issue by jonmoss** [castlegateit/jquery-mapify#2]
Julia has produced a situation where the map auto-centers and zooms such that all points on the map are visible, but then cannot be scrolled, as attempting to move the map is like "fighting" the auto-positioning and results in an unpleasant juddering effect.

I believe we had this issue before with an older map script and it was something to do with overzealous auto-center triggering.

**Comment by johnkhughes** [comment]
Can you show me some code that reproduces the bug?

**Comment by johnkhughes** [comment]
No response and nobody else has reported it, so I'm going to close this now.
